### ISSUE TITLE
Responsive Typography error while rendering the channel title in VideoDetail.jsx page

### ISSUE THREAD

**Issue by iampsr8** [adrianhajdin/project_youtube_clone#4]
### will give an error of invalid prop variant passed
![Screenshot 2022-08-30 215046](https://user-images.githubusercontent.com/78249809/187489498-65b3fa79-1f25-4a7c-89c1-02f7f284e2db.png)

**Comment by fatkungfu** [comment]
i fix it by change it to this
`<Typography variant="h6" color="#fff" >{channelTitle} </Typography>`

**Comment by dmalvi2002** [comment]
Please change variant value from "body1" to "subtitle1" or "subtitle2". That should fix it.
